### ISSUE TITLE
Error while running python main.py

### ISSUE THREAD

**Issue by azharlightelligence** [jaimervq/all_nodes#45]
Hi, I got this traceback , although I have successfully installed the requirement.txt but: ~/workspace/nodegraphs/all_nodes$ python main.py 
Traceback (most recent call last):
  File "main.py", line 14, in <module>
    from all_nodes.analytics import analytics
  File "/gate/homes/me/miniconda3/envs/py38/lib/python3.8/site-packages/shiboken2/files.dir/shibokensupport/__feature__.py", line 144, in _import
    return original_import(name, *args, **kwargs)
ModuleNotFoundError: No module named 'all_nodes'

Please help how to resolve this issue? thanks

**Comment by jaimervq** [comment]
Hi! Thanks for raising this issue.

It seems to me that this package has not been added to your `PYTHONPATH` variable before running main.py

For that, if in WINDOWS, you could do the following:
Lets assume your `all_nodes` is in the folder `D:\python\all_nodes`. You would do in your terminal
```
set PYTHONPATH=D:\python;%PYTHONPATH%
```
Or, even easier, to just the parent directory of where the `all_nodes` is
```
set PYTHONPATH=D:\python\..\;%PYTHONPATH%
```

If in Linux, you would set the env variable like this:
https://www.serverlab.ca/tutorials/linux/administration-linux/how-to-set-environment-variables-in-linux/

Cheers!

**Comment by azharlightelligence** [comment]
Thanks that solved it!
